import type { Metadata } from "next";
import { Cairo, Figtree } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ToastProvider } from "@/providers/ToastProvider";
import ActiveMenuProvider from "@/providers/ActiveMenuProvider";
import QueryProvider from "@/providers/QueryProvider";
import { RepliesStateProvider } from "@/providers/RepliesStateProvider";
const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });
// ========================================
const cairo = Cairo({
  subsets: ["arabic"],
  weight: ["1000", "400", "500", "600", "700", "800", "900", "300"],
});

export const metadata: Metadata = {
  title: "FlowNet",
  description: "Generated by create next app",
  icons: "favicon.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      dir="rtl"
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        cairo.className,
        "font-sans",
        figtree.variable,
      )}
    >
      <body className="min-h-full flex flex-col bg-[#19191d] text-white">
        <RepliesStateProvider>
          <ActiveMenuProvider>
            <TooltipProvider>
              <QueryProvider>
                <ToastProvider> {children}</ToastProvider>
              </QueryProvider>
            </TooltipProvider>
          </ActiveMenuProvider>
        </RepliesStateProvider>
      </body>
    </html>
  );
}
