import type { Metadata } from "next";
import { Tajawal } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ToastProvider } from "@/providers/ToastProvider";
import ActiveMenuProvider from "@/providers/ActiveMenuProvider";
import QueryProvider from "@/providers/QueryProvider";
import { RepliesStateProvider } from "@/providers/RepliesStateProvider";
import { UserProvider } from "@/providers/UserProvider";
import GetSession from "@/auth/GetSession";
// ========================================
const tajawal = Tajawal({
  subsets: ["arabic"],
  weight: ["400", "500", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Maglis",
  description: "Generated by create next app",
  icons: "favicon.png",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await GetSession();
  return (
    <html
      dir="rtl"
      lang="en"
      className={cn("h-full", "antialiased", tajawal.className, "font-sans")}
    >
      <body className="min-h-full flex flex-col bg-[#19191d] text-white">
        <UserProvider user={session}>
          <RepliesStateProvider>
            <ActiveMenuProvider>
              <TooltipProvider>
                <QueryProvider>
                  <ToastProvider> {children}</ToastProvider>
                </QueryProvider>
              </TooltipProvider>
            </ActiveMenuProvider>
          </RepliesStateProvider>
        </UserProvider>
      </body>
    </html>
  );
}
