export const dynamic = "force-dynamic";
import type { Metadata } from "next";
import { Tajawal } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Providers from "@/app/Providers";
// ========================================
const tajawal = Tajawal({
  subsets: ["arabic"],
  weight: ["300", "400", "500", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Maglis",
  description: "Generated by create next app",
  icons: "favicon.png",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      dir="rtl"
      lang="en"
      className={cn("h-full", "antialiased", tajawal.className, "font-sans")}
    >
      <body className="min-h-full flex flex-col bg-[#0F0F0F] text-white font-light">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
